package com.example.animalcrossingdesign

class AnimalCrossingColors {
    val animalCrossingPaletteColors = mutableMapOf<Byte, Int>()

    init {
        animalCrossingPaletteColors[0x00.toByte()] = 0xffffefff.toInt()
        animalCrossingPaletteColors[0x01.toByte()] = 0xffff9aad.toInt()
        animalCrossingPaletteColors[0x02.toByte()] = 0xffef559c.toInt()
        animalCrossingPaletteColors[0x03.toByte()] = 0xffff65ad.toInt()
        animalCrossingPaletteColors[0x04.toByte()] = 0xffff0063.toInt()
        animalCrossingPaletteColors[0x05.toByte()] = 0xffbd4573.toInt()
        animalCrossingPaletteColors[0x06.toByte()] = 0xffce0052.toInt()
        animalCrossingPaletteColors[0x07.toByte()] = 0xff9c0031.toInt()
        animalCrossingPaletteColors[0x08.toByte()] = 0xff522031.toInt()

        animalCrossingPaletteColors[0x10.toByte()] = 0xffffbace.toInt()
        animalCrossingPaletteColors[0x11.toByte()] = 0xffff7573.toInt()
        animalCrossingPaletteColors[0x12.toByte()] = 0xffde3010.toInt()
        animalCrossingPaletteColors[0x13.toByte()] = 0xffff5542.toInt()
        animalCrossingPaletteColors[0x14.toByte()] = 0xffff0000.toInt()
        animalCrossingPaletteColors[0x15.toByte()] = 0xffce6563.toInt()
        animalCrossingPaletteColors[0x16.toByte()] = 0xffbd4542.toInt()
        animalCrossingPaletteColors[0x17.toByte()] = 0xffbd0000.toInt()
        animalCrossingPaletteColors[0x18.toByte()] = 0xff8c2021.toInt()

        animalCrossingPaletteColors[0x20.toByte()] = 0xffdecfbd.toInt()
        animalCrossingPaletteColors[0x21.toByte()] = 0xffffcf63.toInt()
        animalCrossingPaletteColors[0x22.toByte()] = 0xffde6521.toInt()
        animalCrossingPaletteColors[0x23.toByte()] = 0xffffaa21.toInt()
        animalCrossingPaletteColors[0x24.toByte()] = 0xffff6500.toInt()
        animalCrossingPaletteColors[0x25.toByte()] = 0xffbd8a52.toInt()
        animalCrossingPaletteColors[0x26.toByte()] = 0xffde4500.toInt()
        animalCrossingPaletteColors[0x27.toByte()] = 0xffbd4500.toInt()
        animalCrossingPaletteColors[0x28.toByte()] = 0xff633010.toInt()

        animalCrossingPaletteColors[0x30.toByte()] = 0xffffefde.toInt()
        animalCrossingPaletteColors[0x31.toByte()] = 0xffffdfce.toInt()
        animalCrossingPaletteColors[0x32.toByte()] = 0xffffcfad.toInt()
        animalCrossingPaletteColors[0x33.toByte()] = 0xffffba8c.toInt()
        animalCrossingPaletteColors[0x34.toByte()] = 0xffffaa8c.toInt()
        animalCrossingPaletteColors[0x35.toByte()] = 0xffde8a63.toInt()
        animalCrossingPaletteColors[0x36.toByte()] = 0xffbd6542.toInt()
        animalCrossingPaletteColors[0x37.toByte()] = 0xff9c5531.toInt()
        animalCrossingPaletteColors[0x38.toByte()] = 0xff8c4521.toInt()

        animalCrossingPaletteColors[0x40.toByte()] = 0xffffcfff.toInt()
        animalCrossingPaletteColors[0x41.toByte()] = 0xffef8aff.toInt()
        animalCrossingPaletteColors[0x42.toByte()] = 0xffce65de.toInt()
        animalCrossingPaletteColors[0x43.toByte()] = 0xffbd8ace.toInt()
        animalCrossingPaletteColors[0x44.toByte()] = 0xffce00ff.toInt()
        animalCrossingPaletteColors[0x45.toByte()] = 0xff9c659c.toInt()
        animalCrossingPaletteColors[0x46.toByte()] = 0xff8c00ad.toInt()
        animalCrossingPaletteColors[0x47.toByte()] = 0xff520073.toInt()
        animalCrossingPaletteColors[0x48.toByte()] = 0xff310042.toInt()

        animalCrossingPaletteColors[0x50.toByte()] = 0xffffbaff.toInt()
        animalCrossingPaletteColors[0x51.toByte()] = 0xffff9aff.toInt()
        animalCrossingPaletteColors[0x52.toByte()] = 0xffde20bd.toInt()
        animalCrossingPaletteColors[0x53.toByte()] = 0xffff55ef.toInt()
        animalCrossingPaletteColors[0x54.toByte()] = 0xffff00ce.toInt()
        animalCrossingPaletteColors[0x55.toByte()] = 0xff8c5573.toInt()
        animalCrossingPaletteColors[0x56.toByte()] = 0xffbd009c.toInt()
        animalCrossingPaletteColors[0x57.toByte()] = 0xff8c0063.toInt()
        animalCrossingPaletteColors[0x58.toByte()] = 0xff520042.toInt()

        animalCrossingPaletteColors[0x60.toByte()] = 0xffdeba9c.toInt()
        animalCrossingPaletteColors[0x61.toByte()] = 0xffceaa73.toInt()
        animalCrossingPaletteColors[0x62.toByte()] = 0xff734531.toInt()
        animalCrossingPaletteColors[0x63.toByte()] = 0xffad7542.toInt()
        animalCrossingPaletteColors[0x64.toByte()] = 0xff9c3000.toInt()
        animalCrossingPaletteColors[0x65.toByte()] = 0xff733021.toInt()
        animalCrossingPaletteColors[0x66.toByte()] = 0xff522000.toInt()
        animalCrossingPaletteColors[0x67.toByte()] = 0xff311000.toInt()
        animalCrossingPaletteColors[0x68.toByte()] = 0xff211000.toInt()

        animalCrossingPaletteColors[0x70.toByte()] = 0xffffffce.toInt()
        animalCrossingPaletteColors[0x71.toByte()] = 0xffffff73.toInt()
        animalCrossingPaletteColors[0x72.toByte()] = 0xffdedf21.toInt()
        animalCrossingPaletteColors[0x73.toByte()] = 0xffffff00.toInt()
        animalCrossingPaletteColors[0x74.toByte()] = 0xffffdf00.toInt()
        animalCrossingPaletteColors[0x75.toByte()] = 0xffceaa00.toInt()
        animalCrossingPaletteColors[0x76.toByte()] = 0xff9c9a00.toInt()
        animalCrossingPaletteColors[0x77.toByte()] = 0xff8c7500.toInt()
        animalCrossingPaletteColors[0x78.toByte()] = 0xff525500.toInt()

        animalCrossingPaletteColors[0x80.toByte()] = 0xffdebaff.toInt()
        animalCrossingPaletteColors[0x81.toByte()] = 0xffbd9aef.toInt()
        animalCrossingPaletteColors[0x82.toByte()] = 0xff6330ce.toInt()
        animalCrossingPaletteColors[0x83.toByte()] = 0xff9c55ff.toInt()
        animalCrossingPaletteColors[0x84.toByte()] = 0xff6300ff.toInt()
        animalCrossingPaletteColors[0x85.toByte()] = 0xff52458c.toInt()
        animalCrossingPaletteColors[0x86.toByte()] = 0xff42009c.toInt()
        animalCrossingPaletteColors[0x87.toByte()] = 0xff210063.toInt()
        animalCrossingPaletteColors[0x88.toByte()] = 0xff211031.toInt()

        animalCrossingPaletteColors[0x90.toByte()] = 0xffbdbaff.toInt()
        animalCrossingPaletteColors[0x91.toByte()] = 0xff8c9aff.toInt()
        animalCrossingPaletteColors[0x92.toByte()] = 0xff3130ad.toInt()
        animalCrossingPaletteColors[0x93.toByte()] = 0xff3155ef.toInt()
        animalCrossingPaletteColors[0x94.toByte()] = 0xff0000ff.toInt()
        animalCrossingPaletteColors[0x95.toByte()] = 0xff31308c.toInt()
        animalCrossingPaletteColors[0x96.toByte()] = 0xff0000ad.toInt()
        animalCrossingPaletteColors[0x97.toByte()] = 0xff101063.toInt()
        animalCrossingPaletteColors[0x98.toByte()] = 0xff000021.toInt()

        animalCrossingPaletteColors[0xa0.toByte()] = 0xff9cefbd.toInt()
        animalCrossingPaletteColors[0xa1.toByte()] = 0xff63cf73.toInt()
        animalCrossingPaletteColors[0xa2.toByte()] = 0xff216510.toInt()
        animalCrossingPaletteColors[0xa3.toByte()] = 0xff42aa31.toInt()
        animalCrossingPaletteColors[0xa4.toByte()] = 0xff008a31.toInt()
        animalCrossingPaletteColors[0xa5.toByte()] = 0xff527552.toInt()
        animalCrossingPaletteColors[0xa6.toByte()] = 0xff215500.toInt()
        animalCrossingPaletteColors[0xa7.toByte()] = 0xff103021.toInt()
        animalCrossingPaletteColors[0xa8.toByte()] = 0xff002010.toInt()

        animalCrossingPaletteColors[0xb0.toByte()] = 0xffdeffbd.toInt()
        animalCrossingPaletteColors[0xb1.toByte()] = 0xffceff8c.toInt()
        animalCrossingPaletteColors[0xb2.toByte()] = 0xff8caa52.toInt()
        animalCrossingPaletteColors[0xb3.toByte()] = 0xffaddf8c.toInt()
        animalCrossingPaletteColors[0xb4.toByte()] = 0xff8cff00.toInt()
        animalCrossingPaletteColors[0xb5.toByte()] = 0xffadba9c.toInt()
        animalCrossingPaletteColors[0xb6.toByte()] = 0xff63ba00.toInt()
        animalCrossingPaletteColors[0xb7.toByte()] = 0xff529a00.toInt()
        animalCrossingPaletteColors[0xb8.toByte()] = 0xff316500.toInt()

        animalCrossingPaletteColors[0xc0.toByte()] = 0xffbddfff.toInt()
        animalCrossingPaletteColors[0xc1.toByte()] = 0xff73cfff.toInt()
        animalCrossingPaletteColors[0xc2.toByte()] = 0xff31559c.toInt()
        animalCrossingPaletteColors[0xc3.toByte()] = 0xff639aff.toInt()
        animalCrossingPaletteColors[0xc4.toByte()] = 0xff1075ff.toInt()
        animalCrossingPaletteColors[0xc5.toByte()] = 0xff4275ad.toInt()
        animalCrossingPaletteColors[0xc6.toByte()] = 0xff214573.toInt()
        animalCrossingPaletteColors[0xc7.toByte()] = 0xff002073.toInt()
        animalCrossingPaletteColors[0xc8.toByte()] = 0xff001042.toInt()

        animalCrossingPaletteColors[0xd0.toByte()] = 0xffadffff.toInt()
        animalCrossingPaletteColors[0xd1.toByte()] = 0xff52ffff.toInt()
        animalCrossingPaletteColors[0xd2.toByte()] = 0xff008abd.toInt()
        animalCrossingPaletteColors[0xd3.toByte()] = 0xff52bace.toInt()
        animalCrossingPaletteColors[0xd4.toByte()] = 0xff00cfff.toInt()
        animalCrossingPaletteColors[0xd5.toByte()] = 0xff429aad.toInt()
        animalCrossingPaletteColors[0xd6.toByte()] = 0xff00658c.toInt()
        animalCrossingPaletteColors[0xd7.toByte()] = 0xff004552.toInt()
        animalCrossingPaletteColors[0xd8.toByte()] = 0xff002031.toInt()

        animalCrossingPaletteColors[0xe0.toByte()] = 0xffceffef.toInt()
        animalCrossingPaletteColors[0xe1.toByte()] = 0xffadefde.toInt()
        animalCrossingPaletteColors[0xe2.toByte()] = 0xff31cfad.toInt()
        animalCrossingPaletteColors[0xe3.toByte()] = 0xff52efbd.toInt()
        animalCrossingPaletteColors[0xe4.toByte()] = 0xff00ffce.toInt()
        animalCrossingPaletteColors[0xe5.toByte()] = 0xff73aaad.toInt()
        animalCrossingPaletteColors[0xe6.toByte()] = 0xff00aa9c.toInt()
        animalCrossingPaletteColors[0xe7.toByte()] = 0xff008a73.toInt()
        animalCrossingPaletteColors[0xe8.toByte()] = 0xff004531.toInt()

        animalCrossingPaletteColors[0xf0.toByte()] = 0xffadffad.toInt()
        animalCrossingPaletteColors[0xf1.toByte()] = 0xff73ff73.toInt()
        animalCrossingPaletteColors[0xf2.toByte()] = 0xff63df42.toInt()
        animalCrossingPaletteColors[0xf3.toByte()] = 0xff00ff00.toInt()
        animalCrossingPaletteColors[0xf4.toByte()] = 0xff21df21.toInt()
        animalCrossingPaletteColors[0xf5.toByte()] = 0xff52ba52.toInt()
        animalCrossingPaletteColors[0xf6.toByte()] = 0xff00ba00.toInt()
        animalCrossingPaletteColors[0xf7.toByte()] = 0xff008a00.toInt()
        animalCrossingPaletteColors[0xf8.toByte()] = 0xff214521.toInt()

        animalCrossingPaletteColors[0x0f.toByte()] = 0xffffffff.toInt()
        animalCrossingPaletteColors[0x1f.toByte()] = 0xffefefef.toInt()
        animalCrossingPaletteColors[0x2f.toByte()] = 0xffdedfde.toInt()
        animalCrossingPaletteColors[0x3f.toByte()] = 0xffcecfce.toInt()
        animalCrossingPaletteColors[0x4f.toByte()] = 0xffbdbabd.toInt()
        animalCrossingPaletteColors[0x5f.toByte()] = 0xffadaaad.toInt()
        animalCrossingPaletteColors[0x6f.toByte()] = 0xff9c9a9c.toInt()
        animalCrossingPaletteColors[0x7f.toByte()] = 0xff8c8a8c.toInt()
        animalCrossingPaletteColors[0x8f.toByte()] = 0xff737573.toInt()
        animalCrossingPaletteColors[0x9f.toByte()] = 0xff636563.toInt()
        animalCrossingPaletteColors[0xaf.toByte()] = 0xff525552.toInt()
        animalCrossingPaletteColors[0xbf.toByte()] = 0xff424542.toInt()
        animalCrossingPaletteColors[0xcf.toByte()] = 0xff313031.toInt()
        animalCrossingPaletteColors[0xdf.toByte()] = 0xff212021.toInt()
        animalCrossingPaletteColors[0xef.toByte()] = 0xff000000.toInt()

    }

}